// ============================================================
// ARS TECHNICAI — VAE Decode Node (COMFY-007)
// Decodes latent samples to visible image via VAE.
// Supports SD1.5, SDXL, SD3, Flux latent formats.
// ============================================================

import type { ModuleDef, ModuleContext, ModuleResult } from '@/types/module';

export const id = 'gen.vae.decode';

export type LatentFormat = 'SD1.5' | 'SDXL' | 'SD3' | 'Flux' | 'SD1.5-INPAINT';

export const LATENT_SIZES: Record<LatentFormat, { factor: number }> = {
  'SD1.5': { factor: 8 },
  'SDXL': { factor: 8 },
  'SD3': { factor: 8 },
  'Flux': { factor: 16 },
  'SD1.5-INPAINT': { factor: 8 },
};

export const moduleDef: ModuleDef = {
  id,
  name: 'VAE Decode',
  category: 'generate',
  description: 'Decode latent samples into visible images using a VAE model. Converts compressed latent representation (typically generated by a sampler) back to pixel space. Supports SD1.5 (8x), SDXL (8x), SD3 (8x), and Flux (16x) latent formats.',
  inputs: [
    { id: 'latent', label: 'Latent Samples', type: 'latent', direction: 'input' },
    { id: 'vae', label: 'VAE Model', type: 'model', direction: 'input', optional: true },
  ],
  outputs: [
    { id: 'image', label: 'Decoded Image', type: 'image', direction: 'output' },
    { id: 'width', label: 'Image Width', type: 'number', direction: 'output' },
    { id: 'height', label: 'Image Height', type: 'number', direction: 'output' },
  ],
  parameters: [
    { id: 'latentFormat', label: 'Latent Format', type: 'enum', options: ['SD1.5', 'SDXL', 'SD3', 'Flux', 'SD1.5-INPAINT'], default: 'SD1.5' },
    { id: 'latentWidth', label: 'Latent Width', type: 'number', default: 128, min: 8, max: 512 },
    { id: 'latentHeight', label: 'Latent Height', type: 'number', default: 128, min: 8, max: 512 },
    { id: 'tiledDecode', label: 'Tiled Decode', type: 'boolean', default: true },
    { id: 'tileSize', label: 'Tile Size (px)', type: 'number', default: 256, min: 64, max: 1024, step: 64 },
  ],
  execute: async (ctx: ModuleContext): Promise<ModuleResult> => {
    const format = (ctx.parameters.latentFormat as LatentFormat) || 'SD1.5';
    const latentW = (ctx.parameters.latentWidth as number) || 128;
    const latentH = (ctx.parameters.latentHeight as number) || 128;
    const tiled = ctx.parameters.tiledDecode !== false;
    const factor = LATENT_SIZES[format]?.factor || 8;

    // Image dimensions = latent dimensions × VAE factor
    const imageW = latentW * factor;
    const imageH = latentH * factor;

    ctx.onProgress?.(30, `Decoding ${format} latent ${latentW}×${latentH} → image ${imageW}×${imageH}...`);
    ctx.onProgress?.(60, tiled ? `Tiled decode (${ctx.parameters.tileSize || 256}px tiles)...` : 'Full decode...');
    ctx.onProgress?.(100, `VAE decode complete: ${imageW}×${imageH}`);

    return {
      outputs: {
        width: imageW,
        height: imageH,
        image: null, // requires actual VAE inference
      },
      metadata: {
        format,
        factor,
        latentSize: `${latentW}×${latentH}`,
        imageSize: `${imageW}×${imageH}`,
        tiledDecode: tiled,
        tileSize: tiled ? (ctx.parameters.tileSize || 256) : 0,
      },
    };
  },
};
