/**
 * node_table.ts — print the node catalogue as Markdown.
 *
 * The README's node list is generated by this rather than typed, because a
 * hand-written table of 30 node types and their ports is a table that is wrong
 * by the next commit. Run it and paste, or diff it against the README:
 *
 *   deno task nodes            the catalogue, grouped by category
 *   deno task nodes --ports    every port of every node, with defaults
 */

import { ALL_NODES } from "../core/catalogue.ts";
import type { NodeCategory, NodeTypeSpec } from "../core/registry.ts";
import type { PortSpec } from "../core/ports.ts";

const CATEGORY_TITLE: Record<NodeCategory, string> = {
  source: "Sources",
  stage: "Restoration stages",
  mask: "Segmentation",
  flow: "Flow and regions",
  ai: "Generative",
  output: "Outputs",
};

const COST_NOTE: Record<NodeTypeSpec["cost"], string> = {
  local: "local",
  filesystem: "disk",
  network: "network",
};

function portList(ports: readonly PortSpec[]): string {
  if (ports.length === 0) return "—";
  return ports
    .map((p) => {
      const marks = [
        p.optional ? "?" : "",
        p.variadic ? "*" : "",
      ].join("");
      return `\`${p.id}${marks}\``;
    })
    .join(" ");
}

function table(nodes: readonly NodeTypeSpec[]): string {
  const rows = nodes.map((n) =>
    `| \`${n.id}\` | ${n.label} | ${COST_NOTE[n.cost]} | ${portList(n.inputs)} | ${
      portList(n.outputs)
    } | ${n.hint} |`
  );
  return [
    "| Type | Name | Runs | Inputs | Outputs | What it is for |",
    "| ---- | ---- | ---- | ------ | ------- | -------------- |",
    ...rows,
  ].join("\n");
}

function main(): void {
  const detail = Deno.args.includes("--ports");

  if (detail) {
    for (const node of ALL_NODES) {
      console.log(`### \`${node.id}\` — ${node.label}\n`);
      console.log(`${node.hint}\n`);
      console.log("| Port | Dir | Kind | Default | Notes |");
      console.log("| ---- | --- | ---- | ------- | ----- |");
      for (const port of [...node.inputs, ...node.outputs]) {
        const def = port.defaultValue && "value" in port.defaultValue
          ? String((port.defaultValue as { value: unknown }).value)
          : port.optional
          ? "optional"
          : "—";
        const notes = [
          port.range ? `${port.range.min}–${port.range.max}${port.range.unit ?? ""}` : "",
          port.options ? `${port.options.length} options` : "",
          port.variadic ? "variadic" : "",
        ].filter(Boolean).join(", ");
        console.log(
          `| \`${port.id}\` | ${port.direction} | ${port.kind} | ${def} | ${notes || port.help} |`,
        );
      }
      console.log("");
    }
    return;
  }

  const byCategory = new Map<NodeCategory, NodeTypeSpec[]>();
  for (const node of ALL_NODES) {
    const list = byCategory.get(node.category) ?? [];
    list.push(node);
    byCategory.set(node.category, list);
  }

  console.log(
    `<!-- generated by \`deno task nodes\` — ${ALL_NODES.length} node types. ` +
      "`?` marks an optional input, `*` a variadic one. -->\n",
  );
  for (const [category, title] of Object.entries(CATEGORY_TITLE) as [NodeCategory, string][]) {
    const nodes = byCategory.get(category);
    if (!nodes || nodes.length === 0) continue;
    console.log(`#### ${title} (${nodes.length})\n`);
    console.log(table(nodes));
    console.log("");
  }
}

if (import.meta.main) main();
